# Generated by Django 5.1.1 on 2024-10-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
