# Generated by Django 5.1.1 on 2024-11-11 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingadress',
            options={'verbose_name_plural': 'Shipping Adress'},
        ),
    ]
