# Generated by Django 5.1.1 on 2024-11-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_shippingadress_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='adress1',
            new_name='shipping_adress1',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='adress2',
            new_name='shipping_adress2',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='city',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='country',
            new_name='shipping_country',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='email',
            new_name='shipping_email',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='full_name',
            new_name='shipping_full_name',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='state',
            new_name='shipping_state',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='zipcode',
            new_name='shipping_zipcode',
        ),
    ]
